- name: Get radarr download clients
  ansible.builtin.uri:
    url: "{{ radarr_api_url }}/downloadclient?apiKey={{ radarr_api_key }}"
    method: GET
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404

- name: Save download clients Json data to a Variable as a Fact
  set_fact:
    qbt_not_configured: "{{ _response.json | json_query('[?name == `qbittorrent`]') | length() == 0 }}"

- name: Add qbittorrent download client
  ansible.builtin.uri:
    url: "{{ radarr_api_url }}/downloadclient?apiKey={{ radarr_api_key }}"
    follow_redirects: none
    method: POST
    body_format: json
    body:
      enable: true
      protocol: torrent
      priority: 1
      removeCompletedDownloads: false
      removeFailedDownloads: true
      name: qbittorrent
      fields:
        - name: host
          value: qbittorrent
        - name: port
          value: '{{ qbt_ui_port }}'
        - name: useSsl
          value: false
        - name: urlBase
        - name: username
          value: "{{ qbt_web_ui_username }}"
        - name: password
          value: "{{ qbt_web_ui_password }}"
        - name: movieCategory
          value: "{{ radarr_qbt_category }}"
        - name: movieImportedCategory
        - name: recentMoviePriority
          value: 0
        - name: olderMoviePriority
          value: 0
        - name: initialState
          value: 0
      implementationName: qBittorrent
      implementation: QBittorrent
      configContract: QBittorrentSettings
      infoLink: 'https://wiki.servarr.com/radarr/supported#qbittorrent'
      tags: []
    status_code: 201
    validate_certs: "{{ validate_certificates }}"
  when: qbt_not_configured
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404 

- name: Add qbittorrent remote mapping
  ansible.builtin.uri:
    url: "{{ radarr_api_url }}/remotepathmapping?apiKey={{ radarr_api_key }}"
    method: POST
    body_format: json
    body:
      host: qbittorrent
      remotePath: "{{ radarr_remote_path_qbt }}"
      localPath: "{{ radarr_remote_path_qbt }}"
    status_code: 201
    validate_certs: "{{ validate_certificates }}"
  when: qbt_not_configured
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404 
