- name: Create TV folder
  community.docker.docker_container_exec:
    container: "{{ sonarr_name }}"
    command: "mkdir -p {{ sonarr_root_folder }}"

- name: Get sonarr volume info
  community.docker.docker_volume_info:
    name: "{{ sonarr_volume }}"
  register: _result

- name: Get sonarr volume path
  ansible.builtin.set_fact:
    sonarr_volume_path: "{{ _result.volume.Mountpoint }}"
  when: _result.exists

- name: Get sonarr API Key
  become: yes
  ansible.builtin.shell:
    cmd: "cat {{ sonarr_volume_path }}/config.xml | grep ApiKey | tr '<' '>' | cut -d '>' -f3"
  register: _response

- name: Save sonarr API key
  ansible.builtin.set_fact:
    sonarr_api_key: "{{ _response.stdout }}"

- name: Set Sonarr API URL
  ansible.builtin.set_fact:
    sonarr_api_url: "http://localhost:{{ sonarr_port }}/api/v3"

- name: Add jackett to sonarr
  ansible.builtin.import_tasks: ./tasks/sonarr/set_rootfolder.yml

- name: Add jackett to sonarr
  ansible.builtin.import_tasks: ./tasks/sonarr/enable_jackett.yml
  when: jackett_enable

- name: Add qbittorrent to sonarr
  ansible.builtin.import_tasks: ./tasks/sonarr/enable_qbt.yml
  when: qbt_enable

- name: Configure exportarr for sonarr
  ansible.builtin.import_tasks: ./tasks/sonarr/configure_exportarr.yml
  when: sonarr_exportarr_enable