- name: Create Movie folder
  ansible.builtin.file:
    path: "{{ folders.media }}/movie"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0750'

- name: Get radarr API Key
  ansible.builtin.shell:
    cmd: "cat {{ folders.config }}/radarr/config.xml | grep ApiKey | tr '<' '>' | cut -d '>' -f3"
  register: _response

- name: Save radarr API key
  ansible.builtin.set_fact:
    radarr_api_key: "{{ _response.stdout }}"

- name: Set radarr API URL
  ansible.builtin.set_fact:
    radarr_api_url: "http://localhost:{{radarr.port}}/api/v3"

- name: Add jackett to radarr
  ansible.builtin.import_tasks: ./tasks/radarr/set_rootfolder.yml

- name: Add jackett to radarr
  ansible.builtin.import_tasks: ./tasks/radarr/enable_jackett.yml
  when: jackett.install

- name: Add qbittorrent to radarr
  ansible.builtin.import_tasks: ./tasks/radarr/enable_qbt.yml
  when: qbittorrent.install
