- name: Create Movie folder
  community.docker.docker_container_exec:
    container: "{{ radarr_name }}"
    command: "mkdir -p {{ radarr_root_folder }}"

- name: Get radarr volume info
  community.docker.docker_volume_info:
    name: "{{ radarr_volume }}"
  register: _result

- name: Get radarr volume path
  ansible.builtin.set_fact:
    radarr_volume_path: "{{ _result.volume.Mountpoint }}"
  when: _result.exists

- name: Get radarr API Key
  become: yes
  ansible.builtin.shell:
    cmd: "cat {{ radarr_volume_path }}/config.xml | grep ApiKey | tr '<' '>' | cut -d '>' -f3"
  register: _response

- name: Save radarr API key
  ansible.builtin.set_fact:
    radarr_api_key: "{{ _response.stdout }}"

- name: Set radarr API URL
  ansible.builtin.set_fact:
    radarr_api_url: "https://{{ radarr_hostname }}.{{ domain }}/api/v3"

- name: Add jackett to radarr
  ansible.builtin.import_tasks: ./tasks/radarr/set_rootfolder.yml

- name: Add jackett to radarr
  ansible.builtin.import_tasks: ./tasks/radarr/enable_jackett.yml
  when: jackett_enable

- name: Add qbittorrent to radarr
  ansible.builtin.import_tasks: ./tasks/radarr/enable_qbt.yml
  when: qbt_enable

- name: Configure exportarr for radarr
  ansible.builtin.import_tasks: ./tasks/radarr/configure_exportarr.yml
  when: radarr_exportarr_enable