- name: Authenticate with qbittorrent using default credentials
  ansible.builtin.uri:
    url: "http://localhost:{{ qbittorrent.ui_port }}/api/v2/auth/login"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ qbittorrent.default_username }}"
      password: "{{ qbittorrent.default_password }}"
    headers:
      Referer: "http://localhost:{{ qbittorrent.ui_port }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 

- name: Save qbittorrent cookie
  ansible.builtin.set_fact:
    qbt_cookie: "{{ _response.cookies_string }}"

- name: Authenticate with qbittorrent using changed credentials
  ansible.builtin.uri:
    url: "http://localhost:{{ qbittorrent.ui_port }}/api/v2/auth/login"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ qbittorrent.settings.preferences.web_ui_username }}"
      password: "{{ qbittorrent.settings.preferences.web_ui_password }}"
    headers:
      Referer: "http://localhost:{{ qbittorrent.ui_port }}"
  register: _response
  when: qbt_cookie == ""
  retries: 10
  delay: 10
  until: _response.status != -1 

- name: Save qbittorrent cookie
  ansible.builtin.set_fact:
    qbt_cookie: "{{ _response.cookies_string }}"
  when: qbt_cookie == ""

- name: Create folders for categories
  ansible.builtin.file:
    path: "{{ folders.data }}/{{ item.path }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0750'
  with_items: "{{ qbittorrent.settings.categories }}"

- name: Attempt to create categories in qbittorrent
  ansible.builtin.uri:
    url: "http://localhost:{{ qbittorrent.ui_port }}/api/v2/torrents/createCategory"
    method: POST
    body_format: form-urlencoded
    body:
      category: "{{ item.name }}"
      savePath: "{{ item.path }}"
    headers:
      Cookie: "{{ qbt_cookie }}"
    status_code: 200, 409
  with_items: "{{ qbittorrent.settings.categories }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 

- name: Get VueTorrent
  ansible.builtin.git:
    repo: https://github.com/WDaan/VueTorrent.git
    dest: "{{ folders.config }}/qbittorrent/vuetorrent"
    version: latest-release
  when: qbittorrent.settings.preferences.alternative_webui_enabled

- name: Set preferences in qbittorrent
  ansible.builtin.uri:
    url: "http://localhost:{{ qbittorrent.ui_port }}/api/v2/app/setPreferences"
    method: POST
    body_format: form-urlencoded
    body:
      json: "{{ qbittorrent.settings.preferences | to_json }}"
    headers:
      Cookie: "{{ qbt_cookie }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 
