- name: Create project folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0750'
  with_items:
    - "{{ folders.project }}"
    - "{{ folders.config }}"
    - "{{ folders.data }}"
    - "{{ folders.downloads }}"
    - "{{ folders.media }}"

- name: Template docker compose file
  ansible.builtin.template:
    src: ./templates/docker-compose.yml.j2
    dest: "{{ folders.project }}/docker-compose.yml"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0640'

- name: Create docker network {{ network_name }}
  community.docker.docker_network:
    name: "{{ network_name }}"

- name: Create docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
  with_items:
    - "{{ acme_volume }}"

- name: Start docker-compose services
  community.docker.docker_compose:
    project_name: media-server
    project_src: "{{ folders.project }}"