- name: Create project folder
  ansible.builtin.file:
    path: "{{ project_folder }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0750'

- name: Create docker network {{ network_name }}
  community.docker.docker_network:
    name: "{{ network_name }}"

- name: Create docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
  with_items:
    - "{{ acme_volume }}"
    - "{{ qbt_volume }}"
    - "{{ jackett_volume }}"
    - "{{ sonarr_volume }}"
    - "{{ radarr_volume }}"
    - "{{ bazarr_volume }}"
    - "{{ overseerr_volume }}"

- name: Create NFS Data share volume
  community.docker.docker_volume:
    name: "{{ data_volume }}"
    driver: local
    driver_options:
      type: nfs4
      o: "addr={{ nfs_data_server }},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":{{ nfs_data_device }}"
  when: data_volume_type == 'nfs'

- name: Create SMB Data share volume
  community.docker.docker_volume:
    name: "{{ data_volume }}"
    driver: local
    driver_options:
      type: cifs
      o: "username={{ cifs_data_username }},password={{ cifs_data_password }},file_mode=0777,dir_mode=0777"
      device: "//{{ cifs_data_server }}/{{ cifs_data_device }}"
  when: data_volume_type == 'cifs'

- name: Start docker images
  ansible.builtin.import_tasks: ../tasks/docker-compose-up.yml
