- name: Create project folder
  ansible.builtin.file:
    path: "{{ project_folder }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0750'

- name: Template docker compose file
  ansible.builtin.template:
    src: ./templates/docker-compose.yml.j2
    dest: "{{ project_folder }}/docker-compose.yml"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0640'

- name: Create docker network {{ network_name }}
  community.docker.docker_network:
    name: "{{ network_name }}"

- name: Create docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
  with_items:
    - "{{ acme_volume }}"
    - "{{ qbt_volume }}"
    - "{{ jackett_volume }}"
    - "{{ sonarr_volume }}"
    - "{{ radarr_volume }}"
    - "{{ overseerr_volume }}"

- name: Create NFS Data share volume
  community.docker.docker_volume:
    name: "{{ nfs_data_volume }}"
    driver: local
    driver_options:
      type: nfs
      o: "addr={{ nfs_data_server }},nolock,noatime,soft,rw"
      device: ":{{ nfs_data_device }}"

- name: Start docker-compose services
  community.docker.docker_compose:
    project_name: media-server
    project_src: "{{ project_folder }}"
    pull: yes