- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Update system
  ansible.builtin.apt:
    upgrade: dist

- name: Update timezone to {{ timezone }}
  ansible.builtin.timezone:
    name: "{{ timezone }}"
  register: timezone_result

- name: Reboot host
  ansible.builtin.reboot:
  when: timezone_result.changed
