- name: Set overseerr_api variable
  ansible.builtin.set_fact:
    overseerr_api: "https://{{ overseerr_hostname }}.{{ domain }}/api/v1"

- name: Sign in to Overseerr using Plex Auth token
  ansible.builtin.uri:
    url: "{{ overseerr_api }}/auth/plex"
    method: POST
    body_format: json
    body:
      authToken: "{{ overseerr_plex_auth_token }}"
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404

- name: Save Overserr cookie
  ansible.builtin.set_fact:
    overseerr_cookie: "{{ _response.cookies['connect.sid'] }}"

- name: Configure Plex
  ansible.builtin.import_tasks: ../tasks/overseerr/configure_plex.yml

- name: Create Sonarr
  ansible.builtin.import_tasks: ../tasks/overseerr/create_sonarr.yml
  when: sonarr_enable

- name: Create Radarr
  ansible.builtin.import_tasks: ../tasks/overseerr/create_radarr.yml
  when: radarr_enable

- name: Configure Discord notifications
  ansible.builtin.import_tasks: ../tasks/overseerr/configure_discord.yml
  when: overseerr_enable_discord_notifications

- name: Get Overseerr apiKey
  ansible.builtin.uri:
    url: "{{ overseerr_api }}/settings/main"
    method: GET
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404

- name: Save Overserr apiKey
  ansible.builtin.set_fact:
    overseerr_api_key: "{{ _response.json['apiKey'] }}"
