- name: Get radarr servers
  ansible.builtin.uri:
    url: "{{ overseerr_api }}/settings/radarr"
    method: GET
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1

- name: Check for existing radarr servers with same hostname and port
  ansible.builtin.set_fact:
    existing_radarr_ids: "{{ _response.json | json_query(q) }}"
  vars:
    q: "[?hostname == `radarr` && port == `{{ radarr_port }}`].id"

- name: Save existing radarr ID and state
  ansible.builtin.set_fact:
    existing_radarr_id: "{{ existing_radarr_ids[0] | default('') }}"
    existing_radarr: "{{ existing_radarr_ids | length() > 0 }}"

- name: Test radarr connection
  ansible.builtin.uri:
    url: "{{ overseerr_api }}/settings/radarr/test"
    method: POST
    body_format: json
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
    body: |
      {
        "hostname": "radarr",
        "port": {{ radarr_port }},
        "apiKey": "{{ radarr_api_key }}",
        "useSsl": false,
        "baseUrl": ""
      }
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1

- name: Save radarr test response
  ansible.builtin.set_fact:
    radarr_test_response: "{{ _response.json }}"

- name: Find ID of profile {{ overseerr_radarr_profile_name }}
  ansible.builtin.set_fact:
    radarr_profile_ids: "{{ radarr_test_response | json_query(profile_query) }}"
    radarr_language_profile_ids: "{{ radarr_test_response | json_query(language_profile_query) }}"
  vars: 
    profile_query: "profiles[?name == `{{ overseerr_radarr_profile_name }}`].id"
    language_profile_query: "languageProfiles[?name == `{{ overseerr_radarr_language_profile_name }}`].id"

- name: Check that profiles exist and set to default if they don't
  ansible.builtin.set_fact:
    radarr_profile_id: "{{ radarr_profile_ids[0] | default(4) }}"
    radarr_language_profile_id: "{{ radarr_language_profile_ids[0] | default(1) }}"

- name: Get name of the selected profile
  ansible.builtin.set_fact:
    radarr_profile_name: "{{ radarr_test_response | json_query(profile_query) }}"
  vars: 
    profile_query: "profiles[?id == `{{ radarr_profile_id }}`].name"

- name: "{{ existing_radarr | ternary('Updating', 'Creating') }} radarr server configuration"
  ansible.builtin.uri:
    url: "{{ overseerr_api }}/settings/radarr/{{ existing_radarr | ternary(existing_radarr_id, '') }}"
    method: "{{ existing_radarr | ternary('PUT', 'POST') }}"
    body_format: json
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
    body: |
      {
        "name": "radarr",
        "hostname": "{{ radarr_hostname }}",
        "port": {{ radarr_port }},
        "apiKey": "{{ radarr_api_key }}",
        "useSsl": false,
        "baseUrl": "",
        "activeProfileId": {{ radarr_profile_id }},
        "activeProfileName": "{{ radarr_profile_name[0] }}",
        "activeDirectory": "{{ radarr_root_folder }}",
        "is4k": false,
        "minimumAvailability": "In Cinemas",
        "isDefault": true,
        "externalUrl": "https://{{ radarr_hostname }}.{{ domain }}",
        "syncEnabled": true,
        "preventSearch": false
      }
    status_code: "{{ existing_radarr | ternary('200', '201') }}"
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1
