- name: Get sonarr indexers
  uri:
    url: "{{ sonarr_api_url }}/indexer?apiKey={{ sonarr_api_key }}"
    follow_redirects: none
    method: GET
  register: _response
  retries: 10
  delay: 10
  until: auth_response.status != -1

- name: Save whether jackett is already configured
  ansible.builtin.set_fact:
    jackett_not_configured: "{{ _response.json | json_query('[?name == `Jackett`]') | length() == 0 }}"

- name: Configure jackett as indexer
  ansible.builtin.uri:
    url: "{{ sonarr_api_url }}/indexer?apiKey={{ sonarr_api_key }}"
    method: POST
    body_format: json
    body:
      enableRss: true
      enableAutomaticSearch: true
      enableInteractiveSearch: true
      supportsRss: true
      supportsSearch: true
      protocol: torrent
      priority: 25
      name: Jackett
      fields:
        - name: baseUrl
          value: "{{ jackett_torznab_url }}"
        - name: apiPath
          value: /api
        - name: apiKey
          value: '{{ jackett_api_key }}'
        - name: categories
          value: "{{ sonarr_indexer_categories }}"
        - name: animeCategories
          value: "{{ sonarr_indexer_categories }}"
        - name: minimumSeeders
          value: "{{ sonarr_minimum_seeders }}"
        - name: seedCriteria.seedRatio
        - name: seedCriteria.seedTime
        - name: seedCriteria.seasonPackSeedTime
        - name: additionalParameters
      implementationName: Torznab
      implementation: Torznab
      configContract: TorznabSettings
      infoLink: 'https://wiki.servarr.com/sonarr/supported#torznab'
      tags: []
    status_code: 201
  when: jackett_not_configured
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 
