- name: Get sonarr root folder
  ansible.builtin.uri:
    url: "{{ sonarr_api_url }}/rootFolder?apiKey={{ sonarr_api_key }}"
    method: GET
    validate_certs: "{{ validate_certificates }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 
  
- name: Check if a rootfolder exists
  set_fact:
    rootpath_not_set: "{{ _response.json | json_query('[*].path') | length() == 0 }}"

- name: Add sonarr rootfolder
  ansible.builtin.uri:
    url: "{{ sonarr_api_url }}/rootFolder?apiKey={{ sonarr_api_key }}"
    method: POST
    body_format: json
    body:
      path: "{{ sonarr_root_folder }}"
    status_code: 201
    validate_certs: "{{ validate_certificates }}"
  when: rootpath_not_set
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 