---
- name: Install Media server with various configurable services
  
  hosts: all
  
  gather_facts: yes

  vars_files:
    - ../vars.default.yml
    - ../vars.yml

  pre_tasks:
    - name: Setup and update host
      ansible.builtin.import_tasks: ../tasks/setup-host.yml
      become: yes

  roles:
    # Install latest docker
    - name: geerlingguy.docker
      become: yes
      vars:
        docker_install_compose: false
        docker_users: "{{ ansible_facts.user_id }}"
    # Install pip, and python packages for docker and docker-compose
    - name: geerlingguy.pip
      become: yes
      vars:
        pip_install_packages:
            - name: docker
            - name: docker-compose

  tasks:
    - name: Reset connection to reload user changes
      ansible.builtin.meta: reset_connection

    - name: Prepare docker compose project
      ansible.builtin.import_tasks: ../tasks/prepare-compose-project.yml

    - name: Configure QBittorrent
      ansible.builtin.import_tasks: ../tasks/qbittorrent/configure.yml
      when: qbt_enable
    
    - name: Configure Jackett
      ansible.builtin.import_tasks: ../tasks/jackett/configure.yml
      when: jackett_enable

    - name: Configure Sonarr
      ansible.builtin.import_tasks: ../tasks/sonarr/configure.yml
      when: sonarr_enable

    - name: Configure Radarr
      ansible.builtin.import_tasks: ../tasks/radarr/configure.yml
      when: radarr_enable

    - name: Configure Overseerr
      ansible.builtin.import_tasks: ../tasks/overseerr/configure.yml
      when: overseerr_enable
